Ben/find 368 findforge add ways to add more names to
findonflow/find pull request #201
Opened 2022-08-11 11:10 UTC by Bamthelearner

2022-08-11 13:28 UTC, Bamthelearner commented
Everyone can add Forge to the dictionary. 
Only forges that are added to certain name / added to PublicForge arrays are available to users. 

Users with premium forge can mint NFT with 0 platform cut

2022-08-12 15:31 UTC, bjartek requested changes

2022-08-12 15:31 UTC, bjartek commented on contracts/Dandy.cdc
>  				let royalty = MetadataViews.Royalty(receiver: self.platform.getMinterFTReceiver(), cut: self.platform.minterCut!, description: "minter")
can we change this to "Creator"

2022-08-16 19:54 UTC, bjartek approved these changes

2022-08-16 19:55 UTC, merged