Bam/find 962 migrate find lease market
findonflow/find pull request #348
Opened 2023-03-08 15:01 UTC by benbackend

2023-03-08 15:03 UTC, Bamthelearner commented on contracts/FindLeaseMarketDirectOfferSoft.cdc
> -		pub fun getName() : String {
Remove `getName()` which is duplicated with `getLeaseName()`

2023-03-08 15:04 UTC, Bamthelearner commented on contracts/FindLeaseMarketDirectOfferSoft.cdc
> +			self.offerCallback.borrow()!.acceptNonEscrowed(self.getLeaseName())
move the sequence so that the name is first move to the buyer, assert that the buyer gets the lease then release the fund

2023-03-08 15:04 UTC, Bamthelearner commented on contracts/FindLeaseMarketDirectOfferSoft.cdc
> -				self.owner!.address != FIND.status(name).owner!  : "You cannot bid on your own resource"
duplicated with codes below

2023-03-08 15:05 UTC, Bamthelearner commented on contracts/FindMarket.cdc
> +// import FIND from "../contracts/FIND.cdc"
There is another branch importing FIND for full default implementation 
But it requires cadence to fix the way it imports contract so it wouldn't reach storage limit

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -		pub fun setExtentionOnLateBid(_ time: UFix64) {
Remove old lease market code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -
Remove old lease market code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -		//call this to start an auction for this lease
Remove old lease market code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -		access(contract) fun increaseBid(_ name: String, balance: UFix64) {
Remove old lease market code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -		pub fun listForAuction(name :String, auctionStartPrice: UFix64, auctionReservePrice: UFix64, auctionDuration: UFix64, auctionExtensionOnLateBid: UFix64) {
Remove old lease market code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -				emit Register(name: name, owner:lease.profile.address, validUntil: lease.validUntil, lockedUntil: lease.lockedUntil)
emit renew instead of register

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FIND.cdc
> -		//make a bid on a name
Remove old lease market code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FindMarket.cdc
> -		pub let findCut:MetadataViews.Royalty?
remove redundant code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FindMarket.cdc
> +	access(contract)fun getPath(_ type: Type, name:String) : String {
reduce redundant code because FindMarket is imported a lot

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FindMarket.cdc
> -		let identifier = type.identifier
reduce redundant code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FindMarket.cdc
> -		let identifier=type.identifier
reduce redundant code

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FindMarket.cdc
> -	access(account) fun pay(tenant: String, id: UInt64, saleItem: &{SaleItem}, vault: @FungibleToken.Vault, royalty: MetadataViews.Royalties, nftInfo:NFTInfo, cuts:{String : FindMarketCutStruct.Cuts}, r
FindMarket imports FIND now, do not have to pass resolver

2023-03-09 14:33 UTC, Bamthelearner commented on contracts/FindMarketAuctionEscrow.cdc
> -import FIND from "./FIND.cdc"
FindMarket imports FIND now, all Market Options contract can use that

2023-03-09 14:33 UTC, Bamthelearner commented on find_test.go
> -	otu.listNameForSale(oldOwner, testingName)
remove old name market transactions and tests

2023-03-09 14:33 UTC, Bamthelearner commented on find_test.go
> -	t.Run("Should not be able to list old leases for sale", func(t *testing.T) {
remove old name market transactions and tests

2023-03-13 12:02 UTC, bjartek requested changes

2024-01-29 15:01 UTC, closed without merging